//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POS
{
    using System;
    using System.Collections.Generic;
    
    public partial class Category
    {
        public string CatgCode { get; set; }
        public string CatgDesc { get; set; }
        public string DeptCode { get; set; }
        public Nullable<decimal> DiscPer { get; set; }
    }
}
