//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POS
{
    using System;
    using System.Collections.Generic;
    
    public partial class Department
    {
        public string DeptCode { get; set; }
        public string DeptDesc { get; set; }
        public Nullable<decimal> DiscPerc { get; set; }
        public bool Comm { get; set; }
        public Nullable<float> Threshold { get; set; }
    }
}
