//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POS
{
    using System;
    using System.Collections.Generic;
    
    public partial class Location
    {
        public string LocCode { get; set; }
        public string LocName { get; set; }
        public string ContactPerson { get; set; }
        public string Add1 { get; set; }
        public string Add2 { get; set; }
        public string Add3 { get; set; }
        public string Phone { get; set; }
        public string Zip { get; set; }
        public Nullable<float> MarkUP { get; set; }
        public string SalesUpdate { get; set; }
        public string Franchisee { get; set; }
        public string OutsideState { get; set; }
        public string WHCode { get; set; }
        public string WHName { get; set; }
        public string TinNo { get; set; }
        public string ZoneCode { get; set; }
    }
}
