//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POS
{
    using System;
    using System.Collections.Generic;
    
    public partial class Medium
    {
        public string LocCode { get; set; }
        public System.DateTime MediaDate { get; set; }
        public string PaymentCode { get; set; }
        public string PaymentName { get; set; }
        public string CurrCode { get; set; }
        public Nullable<decimal> BuyRate { get; set; }
        public Nullable<decimal> SellRate { get; set; }
        public Nullable<decimal> DrawerAmount { get; set; }
        public Nullable<decimal> DrawerAmountByUser { get; set; }
        public Nullable<decimal> EquivalentAmount { get; set; }
    }
}
