//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POS
{
    using System;
    using System.Collections.Generic;
    
    public partial class plumaster
    {
        public string SkuCode { get; set; }
        public string PluCode { get; set; }
        public Nullable<float> PluQty { get; set; }
        public Nullable<decimal> CostPrice { get; set; }
        public Nullable<decimal> MRP { get; set; }
        public Nullable<decimal> SalePrice { get; set; }
        public Nullable<int> ExpiryMonth { get; set; }
        public Nullable<int> ExpiryYear { get; set; }
        public string EanCode { get; set; }
        public Nullable<int> Priority { get; set; }
        public Nullable<decimal> ACP { get; set; }
        public Nullable<System.DateTime> LUpdatedDate { get; set; }
        public Nullable<decimal> WSPrice { get; set; }
        public string PluShade { get; set; }
        public string ColorCode { get; set; }
        public string SizeCode { get; set; }
        public Nullable<float> PluMBQ { get; set; }
        public string RackNo { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public Nullable<System.DateTime> ExpiryDate { get; set; }
        public Nullable<decimal> ExtraPrice { get; set; }
    }
}
