//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POS
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class RetailManagerDBEntities : DbContext
    {
        public RetailManagerDBEntities()
            : base("name=RetailManagerDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CustdataN> CustdataNs { get; set; }
        public virtual DbSet<Category> Categories { get; set; }
        public virtual DbSet<Brand> Brands { get; set; }
        public virtual DbSet<CurrencyFile> CurrencyFiles { get; set; }
        public virtual DbSet<HSNMaster> HSNMasters { get; set; }
        public virtual DbSet<Location> Locations { get; set; }
        public virtual DbSet<Medium> Media { get; set; }
        public virtual DbSet<PaymentMode> PaymentModes { get; set; }
        public virtual DbSet<plumaster> plumasters { get; set; }
        public virtual DbSet<SkuMaster> SkuMasters { get; set; }
        public virtual DbSet<SkuPrice> SkuPrices { get; set; }
        public virtual DbSet<Stock> Stocks { get; set; }
        public virtual DbSet<SubCatg> SubCatgs { get; set; }
        public virtual DbSet<Supplier> Suppliers { get; set; }
        public virtual DbSet<TaxFile> TaxFiles { get; set; }
        public virtual DbSet<Department> Departments { get; set; }
        public virtual DbSet<vipmaster> vipmasters { get; set; }
    }
}
