//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POS
{
    using System;
    using System.Collections.Generic;
    
    public partial class SkuMaster
    {
        public string SkuCode { get; set; }
        public string SkuDesc { get; set; }
        public Nullable<decimal> Price { get; set; }
        public string CatgCode { get; set; }
        public string TaxCode { get; set; }
        public bool OpenRate { get; set; }
        public bool Kit { get; set; }
        public bool Discountable { get; set; }
        public Nullable<float> Qoh { get; set; }
        public Nullable<float> Rol { get; set; }
        public Nullable<float> Roq { get; set; }
        public Nullable<decimal> Lastcost { get; set; }
        public Nullable<decimal> MinPrice { get; set; }
        public string Remarks { get; set; }
        public Nullable<System.DateTime> EffectiveDate { get; set; }
        public Nullable<decimal> NewPrice { get; set; }
        public string UOM { get; set; }
        public Nullable<System.DateTime> DtPromFrom { get; set; }
        public Nullable<System.DateTime> DtPromTo { get; set; }
        public Nullable<decimal> PromPrice { get; set; }
        public Nullable<decimal> AvgCost { get; set; }
        public Nullable<decimal> CostPrice { get; set; }
        public Nullable<decimal> MRP { get; set; }
        public Nullable<int> ExpiryMonth { get; set; }
        public Nullable<int> ExpiryYear { get; set; }
        public string SubCatgCode { get; set; }
        public string SupplierCode { get; set; }
        public bool EanNumber { get; set; }
        public Nullable<decimal> Markup { get; set; }
        public Nullable<decimal> MarkDown { get; set; }
        public string MfgCode { get; set; }
        public string EanCode { get; set; }
        public string ShortDesc { get; set; }
        public Nullable<float> MBQ { get; set; }
        public Nullable<System.DateTime> LastUpdated { get; set; }
        public Nullable<int> RunningPluNo { get; set; }
        public string BrandCode { get; set; }
        public string PackSize { get; set; }
        public bool Inactive { get; set; }
        public Nullable<int> BestBefore { get; set; }
        public Nullable<float> Indent { get; set; }
        public Nullable<float> OnOrder { get; set; }
        public string RackNo { get; set; }
        public string FrTaxCode { get; set; }
        public bool ToAllLocations { get; set; }
        public bool Consignment { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string UserId { get; set; }
        public Nullable<decimal> Disc1 { get; set; }
        public Nullable<decimal> Disc2 { get; set; }
        public Nullable<decimal> FirstCP { get; set; }
        public Nullable<decimal> WSPrice { get; set; }
        public string CSTTaxCode { get; set; }
        public Nullable<float> MaxBQ { get; set; }
        public string SizeCode { get; set; }
        public string ColorCode { get; set; }
        public string AllowDecimals { get; set; }
        public string WebSKU { get; set; }
        public string Matrix { get; set; }
        public string PatternCode { get; set; }
        public string HSNCode { get; set; }
        public Nullable<decimal> SplCess { get; set; }
    }
}
