//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POS
{
    using System;
    using System.Collections.Generic;
    
    public partial class SkuPrice
    {
        public string LocCode { get; set; }
        public string SkuCode { get; set; }
        public string PluCode { get; set; }
        public string EanCode { get; set; }
        public Nullable<decimal> CostPrice { get; set; }
        public Nullable<decimal> MRP { get; set; }
        public Nullable<decimal> SalePrice { get; set; }
        public Nullable<int> Priority { get; set; }
        public string TaxCode { get; set; }
        public Nullable<bool> OpenRate { get; set; }
        public Nullable<bool> Discountable { get; set; }
        public Nullable<bool> InActive { get; set; }
        public Nullable<bool> NonInventory { get; set; }
    }
}
