//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POS
{
    using System;
    using System.Collections.Generic;
    
    public partial class TaxFile
    {
        public string TaxCode { get; set; }
        public string TaxDesc { get; set; }
        public Nullable<decimal> TaxPerc { get; set; }
        public string CalcSur { get; set; }
    }
}
